public with sharing class ConstantsForPresentation {
  public static final String TITLE_PAGE = 'titlePage';
  public static final String ONE = 'one';
  public static final String TWO = 'two';
  public static final String THREE = 'three';
  public static final String FOUR = 'four';
  public static final String FIVE = 'five';
  public static final String SIX = 'six';
  public static final String SEVEN = 'seven';
  public static final String EIGHT = 'eight';
  public static final String NINE = 'nine';
  public static final String TEN = 'ten';
  public static final String ELEVEN = 'eleven';
  public static final String TWELVE = 'twelve';
  public static final String THIRTEEN = 'thirteen';
  public static final String FOURTEEN = 'fourteen';
}